<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Schedule;
use Carbon\Carbon;

class ScheduleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $schedules = [
            [
                'title' => 'Cơ Bản A1-A2',
                'level' => 'a1-a2',
                'description' => 'Khóa học tiếng Đức cơ bản dành cho người mới bắt đầu. Học viên sẽ được trang bị những kiến thức nền tảng về ngữ pháp, từ vựng và giao tiếp cơ bản.',
                'start_date' => Carbon::now()->addDays(5),
                'end_date' => Carbon::now()->addMonths(6)->addDays(5),
                'schedule_days' => ['monday', 'wednesday', 'friday'],
                'start_time' => '19:00',
                'end_time' => '21:00',
                'duration_months' => 6,
                'max_students' => 15,
                'current_students' => 10,
                'price' => 3500000,
                'original_price' => 4118000,
                'discount_percentage' => 15,
                'teacher_name' => 'Herr Schmidt',
                'teacher_title' => 'Giảng viên bản ngữ Đức',
                'course_type' => 'regular',
                'status' => 'published',
                'is_featured' => false,
                'is_popular' => true,
                'registration_deadline' => Carbon::now()->addDays(3),
                'location' => 'Trung tâm Thanh Cúc - 123 Đường ABC',
                'requirements' => ['Không yêu cầu kiến thức trước', 'Có động lực học tập'],
                'benefits' => ['Nắm vững ngữ pháp cơ bản', 'Giao tiếp được trong các tình huống đơn giản', 'Chuẩn bị tốt cho bậc B1'],
                'curriculum' => ['Bảng chữ cái và phát âm', 'Ngữ pháp cơ bản', 'Từ vựng hàng ngày', 'Giao tiếp cơ bản'],
                'certificate' => 'Chứng chỉ hoàn thành khóa học A1-A2',
                'meta_title' => 'Khóa học tiếng Đức A1-A2 cơ bản tại Thanh Cúc',
                'meta_description' => 'Học tiếng Đức từ cơ bản với khóa A1-A2 tại trung tâm Thanh Cúc. Giảng viên bản ngữ, lịch học linh hoạt.',
                'slug' => 'co-ban-a1-a2',
                'sort_order' => 1
            ],
            [
                'title' => 'Trung Cấp B1-B2',
                'level' => 'b1-b2',
                'description' => 'Khóa học tiếng Đức trung cấp giúp học viên phát triển kỹ năng giao tiếp và chuẩn bị cho các kỳ thi chứng chỉ quốc tế.',
                'start_date' => Carbon::now()->addDays(8),
                'end_date' => Carbon::now()->addMonths(8)->addDays(8),
                'schedule_days' => ['tuesday', 'thursday', 'saturday'],
                'start_time' => '18:30',
                'end_time' => '20:30',
                'duration_months' => 8,
                'max_students' => 12,
                'current_students' => 9,
                'price' => 4200000,
                'original_price' => 4941000,
                'discount_percentage' => 15,
                'teacher_name' => 'Frau Müller',
                'teacher_title' => 'Chuyên gia TestDaF',
                'course_type' => 'regular',
                'status' => 'published',
                'is_featured' => true,
                'is_popular' => false,
                'registration_deadline' => Carbon::now()->addDays(6),
                'location' => 'Trung tâm Thanh Cúc - 123 Đường ABC',
                'requirements' => ['Đã hoàn thành A2 hoặc có kiến thức tương đương', 'Có động lực học tập cao'],
                'benefits' => ['Giao tiếp tự tin trong nhiều tình huống', 'Chuẩn bị tốt cho TestDaF', 'Hiểu được văn bản phức tạp'],
                'curriculum' => ['Ngữ pháp nâng cao', 'Kỹ năng viết', 'Kỹ năng nghe hiểu', 'Thảo luận và tranh luận'],
                'certificate' => 'Chứng chỉ hoàn thành khóa học B1-B2',
                'meta_title' => 'Khóa học tiếng Đức B1-B2 trung cấp tại Thanh Cúc',
                'meta_description' => 'Khóa học tiếng Đức B1-B2 chuẩn bị TestDaF tại Thanh Cúc. Giảng viên chuyên nghiệp, phương pháp hiện đại.',
                'slug' => 'trung-cap-b1-b2',
                'sort_order' => 2
            ],
            [
                'title' => 'Nâng Cao C1-C2',
                'level' => 'c1-c2',
                'description' => 'Khóa học tiếng Đức nâng cao dành cho những học viên muốn đạt trình độ thành thạo và chuẩn bị cho các kỳ thi Goethe C1/C2.',
                'start_date' => Carbon::now()->addDays(12),
                'end_date' => Carbon::now()->addMonths(10)->addDays(12),
                'schedule_days' => ['monday', 'wednesday', 'friday'],
                'start_time' => '19:30',
                'end_time' => '21:30',
                'duration_months' => 10,
                'max_students' => 10,
                'current_students' => 8,
                'price' => 5500000,
                'original_price' => 6471000,
                'discount_percentage' => 15,
                'teacher_name' => 'Herr Weber',
                'teacher_title' => 'Chuyên gia Goethe C1/C2',
                'course_type' => 'intensive',
                'status' => 'published',
                'is_featured' => true,
                'is_popular' => true,
                'registration_deadline' => Carbon::now()->addDays(10),
                'location' => 'Trung tâm Thanh Cúc - 123 Đường ABC',
                'requirements' => ['Đã hoàn thành B2 hoặc có kiến thức tương đương', 'Cam kết học tập nghiêm túc'],
                'benefits' => ['Thành thạo tiếng Đức như người bản ngữ', 'Đạt chứng chỉ Goethe C1/C2', 'Cơ hội việc làm tốt tại Đức'],
                'curriculum' => ['Ngữ pháp phức tạp', 'Văn học và văn hóa Đức', 'Kỹ năng thuyết trình', 'Viết luận chuyên nghiệp'],
                'certificate' => 'Chứng chỉ hoàn thành khóa học C1-C2',
                'meta_title' => 'Khóa học tiếng Đức C1-C2 nâng cao tại Thanh Cúc',
                'meta_description' => 'Khóa học tiếng Đức C1-C2 nâng cao chuẩn bị Goethe tại Thanh Cúc. Đạt trình độ thành thạo như người bản ngữ.',
                'slug' => 'nang-cao-c1-c2',
                'sort_order' => 3
            ],
            [
                'title' => 'Tiếng Đức Thương Mại',
                'level' => 'business',
                'description' => 'Khóa học tiếng Đức chuyên ngành thương mại, giúp học viên giao tiếp hiệu quả trong môi trường kinh doanh quốc tế.',
                'start_date' => Carbon::now()->addDays(15),
                'end_date' => Carbon::now()->addMonths(4)->addDays(15),
                'schedule_days' => ['tuesday', 'thursday'],
                'start_time' => '18:00',
                'end_time' => '20:00',
                'duration_months' => 4,
                'max_students' => 15,
                'current_students' => 7,
                'price' => 2800000,
                'original_price' => 3294000,
                'discount_percentage' => 15,
                'teacher_name' => 'Frau Fischer',
                'teacher_title' => 'Chuyên gia Business German',
                'course_type' => 'regular',
                'status' => 'published',
                'is_featured' => false,
                'is_popular' => false,
                'registration_deadline' => Carbon::now()->addDays(13),
                'location' => 'Trung tâm Thanh Cúc - 123 Đường ABC',
                'requirements' => ['Trình độ B1 trở lên', 'Có kinh nghiệm làm việc hoặc quan tâm đến kinh doanh'],
                'benefits' => ['Giao tiếp tự tin trong môi trường kinh doanh', 'Hiểu biết về văn hóa kinh doanh Đức', 'Cơ hội việc làm tại các công ty Đức'],
                'curriculum' => ['Từ vựng kinh doanh', 'Viết email chuyên nghiệp', 'Thuyết trình kinh doanh', 'Đàm phán và hợp đồng'],
                'certificate' => 'Chứng chỉ tiếng Đức thương mại',
                'meta_title' => 'Khóa học tiếng Đức thương mại tại Thanh Cúc',
                'meta_description' => 'Học tiếng Đức thương mại chuyên nghiệp tại Thanh Cúc. Phát triển kỹ năng giao tiếp kinh doanh hiệu quả.',
                'slug' => 'tieng-duc-thuong-mai',
                'sort_order' => 4
            ],
            [
                'title' => 'Luyện Thi Chứng Chỉ',
                'level' => 'exam',
                'description' => 'Khóa học luyện thi chuyên sâu cho các kỳ thi chứng chỉ tiếng Đức quốc tế như Goethe, TestDaF, telc.',
                'start_date' => Carbon::now()->addDays(18),
                'end_date' => Carbon::now()->addMonths(3)->addDays(18),
                'schedule_days' => ['saturday', 'sunday'],
                'start_time' => '14:00',
                'end_time' => '16:00',
                'duration_months' => 3,
                'max_students' => 12,
                'current_students' => 6,
                'price' => 2200000,
                'original_price' => 2588000,
                'discount_percentage' => 15,
                'teacher_name' => 'Team giảng viên',
                'teacher_title' => 'Chuyên luyện thi',
                'course_type' => 'weekend',
                'status' => 'published',
                'is_featured' => false,
                'is_popular' => false,
                'registration_deadline' => Carbon::now()->addDays(16),
                'location' => 'Trung tâm Thanh Cúc - 123 Đường ABC',
                'requirements' => ['Trình độ tối thiểu A2', 'Có mục tiêu thi chứng chỉ cụ thể'],
                'benefits' => ['Nắm vững cấu trúc đề thi', 'Kỹ thuật làm bài hiệu quả', 'Tỷ lệ đậu cao'],
                'curriculum' => ['Phân tích đề thi', 'Luyện kỹ năng 4 kỹ năng', 'Thi thử định kỳ', 'Tư vấn chiến lược thi'],
                'certificate' => 'Chứng nhận hoàn thành khóa luyện thi',
                'meta_title' => 'Khóa luyện thi chứng chỉ tiếng Đức tại Thanh Cúc',
                'meta_description' => 'Luyện thi chứng chỉ tiếng Đức Goethe, TestDaF tại Thanh Cúc. Tỷ lệ đậu cao, phương pháp hiệu quả.',
                'slug' => 'luyen-thi-chung-chi',
                'sort_order' => 5
            ],
            [
                'title' => 'Học Online A1-B2',
                'level' => 'online',
                'description' => 'Khóa học tiếng Đức online linh hoạt, phù hợp với người bận rộn. Học mọi lúc mọi nơi với giảng viên bản ngữ.',
                'start_date' => Carbon::now()->addDays(1),
                'end_date' => Carbon::now()->addMonths(12)->addDays(1),
                'schedule_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '20:00',
                'end_time' => '21:30',
                'duration_months' => 12,
                'max_students' => 20,
                'current_students' => 15,
                'price' => 2500000,
                'original_price' => 2941000,
                'discount_percentage' => 15,
                'teacher_name' => 'Giảng viên bản ngữ',
                'teacher_title' => 'Chuyên gia học online',
                'course_type' => 'online',
                'status' => 'published',
                'is_featured' => true,
                'is_popular' => true,
                'registration_deadline' => null,
                'location' => 'Online - Zoom/Google Meet',
                'requirements' => ['Có máy tính/điện thoại kết nối internet', 'Cam kết học tập đều đặn'],
                'benefits' => ['Học linh hoạt theo thời gian', 'Tiết kiệm chi phí đi lại', 'Tương tác trực tiếp với giảng viên'],
                'curriculum' => ['Video bài giảng', 'Bài tập tương tác', 'Lớp học trực tuyến', 'Hỗ trợ 24/7'],
                'certificate' => 'Chứng chỉ học online',
                'meta_title' => 'Khóa học tiếng Đức online tại Thanh Cúc',
                'meta_description' => 'Học tiếng Đức online linh hoạt tại Thanh Cúc. Giảng viên bản ngữ, lịch học tự do, học phí hợp lý.',
                'slug' => 'hoc-online-a1-b2',
                'sort_order' => 6
            ]
        ];

        foreach ($schedules as $scheduleData) {
            Schedule::create($scheduleData);
        }
    }
}